# -*- coding: utf-8 -*-
"""Evs Stable Diffusion WebUI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12rQPpW4ERyvivIUe1KDlm0jTdKYnyeo5

**Click everything in order once even if it turns red move on to the next one:**
"""

!nvidia-smi
import os

Mount_Drive = True #@param {'type':'boolean'}
Unmount_Drive = False #@param {'type':'boolean'}

if Mount_Drive:
  from google.colab import drive
  drive.mount('/content/drive')
if Unmount_Drive:
  from google.colab import drive
  drive.flush_and_unmount()

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
# %cd stable-diffusion-webui/extensions

!git clone https://github.com/fkunn1326/openpose-editor
!git clone https://github.com/Mikubill/sd-webui-controlnet
!git clone https://github.com/kohya-ss/sd-webui-additional-networks
!git clone https://github.com/DominikDoom/a1111-sd-webui-tagcomplete
!git clone https://github.com/nonnonstop/sd-webui-3d-open-pose-editor
!git clone https://github.com/yfszzx/stable-diffusion-webui-images-browser
!git clone https://github.com/hnmr293/sd-webui-llul
!git clone https://github.com/imrayya/stable-diffusion-webui-Prompt_Generator
!git clone https://github.com/7eu7d7/DreamArtist-sd-webui-extension
!git clone https://github.com/klimaleksus/stable-diffusion-webui-conditioning-highres-fix
!git clone https://github.com/dustysys/ddetailer

!COMMANDLINE_ARGS="--exit" REQS_FILE="requirements.txt" python launch.py
os.kill(os.getpid(), 9)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/stable-diffusion-webui/models/Stable-diffusion
!wget https://huggingface.co/zylux/orangechillmix/resolve/main/orangechillmix_v70.safetensors
!wget https://civitai.com/api/download/models/63634 --content-disposition
!wget https://civitai.com/api/download/models/60790 --content-disposition
!wget https://huggingface.co/theintuitiveye/HARDblend/resolve/main/HARDblend.safetensors

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/stable-diffusion-webui/embeddings
!wget https://huggingface.co/zylux/orangechillmix/resolve/main/bad-picture-chill-75v.pt
!wget https://huggingface.co/zylux/orangechillmix/resolve/main/ng_deepnegative_v1_75t.pt
!wget https://huggingface.co/zylux/orangechillmix/resolve/main/By%20bad%20artist%20-neg.pt
!wget https://huggingface.co/zylux/orangechillmix/resolve/main/bad-picture-chill-75v.pt
!wget https://huggingface.co/zylux/orangechillmix/resolve/main/badhandsv5-neg.pt
!wget https://huggingface.co/zylux/orangechillmix/resolve/main/badhandv4.pt
!wget https://huggingface.co/embed/negative/resolve/main/EasyNegativeV2.safetensors
!wget https://huggingface.co/zylux/orangechillmix/resolve/main/verybadimagenegative_v1.3.pt
!wget https://huggingface.co/zylux/orangechillmix/resolve/main/bad_prompt_version2.pt
!wget https://huggingface.co/zylux/orangechillmix/resolve/main/negative_hand-neg.pt

"""##### Put your LoRA models here"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/stable-diffusion-webui/models/VAE
!wget https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.ckpt

# Commented out IPython magic to ensure Python compatibility.
!mkdir /content/stable-diffusion-webui/models/Lora

# %cd /content/stable-diffusion-webui/models/Lora
!wget https://huggingface.co/Evilixie/portals/resolve/main/PORTALSFINISHEDLATEST.safetensors
!wget https://huggingface.co/Evilixie/portals/resolve/main/Nymphie-000100.safetensors
!wget https://huggingface.co/Evilixie/portals/resolve/main/PORTALSFIX-000132.safetensors
!wget https://huggingface.co/Evilixie/portals/resolve/main/Nymphie-000050.safetensors
!wget https://huggingface.co/Evilixie/portals/resolve/main/Nymphie-000070.safetensors
!wget https://huggingface.co/Evilixie/portals/resolve/main/Nymphie-000060.safetensors

"""##### Enjoy"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/stable-diffusion-webui
!git pull

!COMMANDLINE_ARGS="--share --gradio-debug --disable-safe-unpickle --no-half-vae" REQS_FILE="requirements.txt" python launch.py